apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: tomcat
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat1
  labels:
    name: tomcat
spec:
  hostname: tomcat-1
  subdomain: default-subdomain
  containers:
  - image: tomcat
    command:
      - sleep
      - "3600"
    name: tomcat
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat2
  labels:
    name: tomcat
spec:
  hostname: tomcat-2
  subdomain: default-subdomain
  containers:
  - image: tomcat
    command:
      - sleep
      - "3600"
    name: tomcat